name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint and run integration tests
      run: |
        npm ci
        npm run lint
        npm test
      env:
        CI: true
        VENDOR_API_KEY: ${{secrets.VENDOR_API_KEY}}
        USER_API_KEY: ${{secrets.USER_API_KEY}}
        COMPANY_UUID: ${{secrets.COMPANY_UUID}}
        TEST_MESSAGE_ID: ${{secrets.TEST_MESSAGE_ID}}
